### ISSUE TITLE
这个库有非 seajs 打包的版本吗？

### ISSUE THREAD

**Issue by chuangbo** [aralejs/cookie#1]
hi，支付宝的兄弟你们好，

我在 https://github.com/chuangbo/meteor-cookie 这个 meteor 的 package 里使用了你们这个原先放在 seajs modules 里的代码，我希望可以直接以 submodule 的方式引入这里的代码，而不是复制粘贴。

谢谢。

**Comment by vczero** [comment]
我也写了一个cookie的工具类，没使用seajs，@chuangbo 。地址：https://github.com/vczero/cookie

**Comment by afc163** [comment]
源码是 CommonJS 的，和 seajs 半毛钱关系没有。

**Comment by vczero** [comment]
哈，半分钱~标题党。就是写完了，看看其他人有没有需求。
